[[language]]
name = "python"
language-servers = ["basedpyright", "ruff"]
auto-format = false

[language-server.ruff]
command = "ruff"
args = ["server"]
only-features = ["format"]

[language-server.basedpyright]
command = "basedpyright-langserver"
args = ["--stdio"]
